version: '3.8'
services:
  frontend:
    container_name: frontend
    build: ./Frontend
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    restart: always
  backend:
    container_name: backend
    build: ./Backend
    environment:
      - NODE_ENV=production
    ports:
      - 8000:80
    restart: always
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: segmentation
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - postgres
    restart: unless-stopped
volumes:
  postgres_data:
