version: '3.8'
services:
  frontend:
    container_name: frontend
    build: ./Frontend
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    restart: always
  backend:
    container_name: backend
    build: ./Backend
    environment:
      - NODE_ENV=production
    ports:
      - 8000:80
    restart: always
